### PR TITLE
Update bioresources documentation and remove deprecated files

### PR DESCRIPTION
**Pull request by bgyori**
This PR updates the README for bioresources with up-to-date instructions for how resources can be extended. As far as I could tell, the following files/code were deprecated and are removed by this PR:
- Version controlled tsv.gz files in the kb/ner folder - these are now in principle generated on the fly
- The ner_kb.config configuration file
- Constants identifying paths to bioresource tsv files in ReachKBConstants.scala - these are now declared in application.conf

Let's see if any tests fail after these changes, I can revert some removals if they are in fact being used.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks @bgyori !

@kwalcock : can you please check on the compilation issues here?

**Comment by MihaiSurdeanu** [comment]
Yep!

**Comment by kwalcock** [comment]
As @bgyori probably saw:
```
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestComplexResolutions.scala:89:23: not found: value StaticProteinFamilyOrComplexFilename
[error] Error occurred in an application involving default arguments.
[error]     kbFilename = Some(StaticProteinFamilyOrComplexFilename),
[error]                       ^
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestFamilyResolutions.scala:348:23: not found: value StaticProteinFamily2Filename
[error] Error occurred in an application involving default arguments.
[error]     kbFilename = Some(StaticProteinFamily2Filename),
[error]                       ^
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestFamilyResolutions.scala:363:23: not found: value StaticProteinFamilyOrComplexFilename
[error] Error occurred in an application involving default arguments.
[error]     kbFilename = Some(StaticProteinFamilyOrComplexFilename),
[error]                       ^
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestOrganResolutions.scala:71:49: not found: value ContextOrganFilename
[error] Error occurred in an application involving default arguments.
[error]   val meta = new IMKBMetaInfo(kbFilename = Some(ContextOrganFilename))
[error]                                                 ^
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestProteinResolutions.scala:21:36: not found: value StaticProteinFilename
[error]   val imkbP0F = new TestProteinKBL(StaticProteinFilename)          // defined after this class (LOOK BELOW)
[error]                                    ^
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestProteinResolutions.scala:22:36: not found: value StaticProteinFilename2
[error]   val imkbPGP = new TestProteinKBL(StaticProteinFilename2)
[error]                                    ^
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestProteinResolutions.scala:23:36: not found: value StaticProteinFilename3
[error]   val imkbPQZ = new TestProteinKBL(StaticProteinFilename3)
[error]                                    ^
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestTsvKBs.scala:118:23: not found: value StaticCellLocation2Filename
[error] Error occurred in an application involving default arguments.
[error]     kbFilename = Some(StaticCellLocation2Filename),
[error]                       ^
[error] /var/jenkins_home/workspace/reach_bioresources_docs/main/src/test/scala/org/clulab/reach/TestTsvKBs.scala:128:23: not found: value StaticProteinFamily2Filename
[error] Error occurred in an application involving default arguments.
[error]     kbFilename = Some(StaticProteinFamily2Filename),
[error]                       ^
[error] 9 errors found
```

**Comment by bgyori** [comment]
So I think the tests could be changed to read the same file paths from application.conf instead of the redundant variable declarations in ReachKBConstants, I'm just not sure how to best implement that in Scala. Would @enoriega or @kwalcock be able to help with that? Thanks!

**Comment by enoriega** [comment]
I'll take care of it

**Comment by kwalcock** [comment]
Thanks for beating me to it, @enoriega.

**Comment by enoriega** [comment]
Looks fine now. Do you want to take a quick look into the tests before merging? @kwalcock

**Pull request merged**
