### PR TITLE
Update paxtools-core dependency to 4.3.1

### PR DESCRIPTION
**Pull request by jmuhlich**
BioPAX is now officially releasing to Maven Central as of PaxTools 4.3.1, so
let's make use of that. (See https://groups.google.com/d/msg/biopax-discuss/zwtwDG23T1E/Vu1OK7iXBQAJ for the release announcement mentioning Maven Central)

### CODE REVIEW

**Comment by myedibleenso** [comment]
Thanks, @jmuhlich.  I think that means we should get rid of this, too: 

https://github.com/jmuhlich/reach/blob/5d0d3486901dfe92d6065bbed7f070644c2454f4/build.sbt#L66-L69

**Comment by jmuhlich** [comment]
They mention that snapshots will be available at https://oss.sonatype.org/content/groups/public/ . Does that need to be included in `resolvers` explicitly?

**Comment by myedibleenso** [comment]
We're not really making use of snapshots for this dependency, but I suppose it doesn't hurt.  

Based on [the sbt reference](http://www.scala-sbt.org/0.13/docs/Resolvers.html), I think the block I linked to could be replaced with this line: 

````scala
resolvers += Resolver.sonatypeRepo("public")
```

**Comment by jmuhlich** [comment]
`Resolver.sonatypeRepo("public")` becomes `https://oss.sonatype.org/content/repositories/snapshots/` which is different from the URL given in the google groups post, `https://oss.sonatype.org/content/groups/public/`. Both have `org/biopax/paxtools/paxtools-core` but the contents are different. I am not a Java guy so I don't know what to make of this.

**Comment by myedibleenso** [comment]
Oh, thanks!  I just tried several different resolvers, but none of them were able to find a `4.3.1-SNAPSHOT`.

We really don't need snapshot versions for this dependency, so let's just keep it simple and remove those resolvers.

**Comment by jmuhlich** [comment]
OK, pushed another commit removing `resolvers`.

**Pull request merged**
