### PR TITLE
Configure jenkins

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
Jenkins *seems* to be working, but so does Travis, and maybe this is therefore unnecessary.  I'll let somebody else decide.  If this is checked in, tests will run on Jenkins and I will unconfigure the tests on Travis.

**Comment by MihaiSurdeanu** [comment]
Hey @kwalcock: should .travis.yml be renamed something else as well?

**Comment by kwalcock** [comment]
That file can remain.  Travis gets disabled elsewhere, via its own control panel.

**Comment by MihaiSurdeanu** [comment]
Cool. Then, ready to merge?

**Comment by MihaiSurdeanu** [comment]
Thanks!


On October 18, 2019 at 9:06:47 AM, Keith Alcock (notifications@github.com)
wrote:

Merged #642 <https://github.com/clulab/reach/pull/642> into master.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/reach/pull/642?email_source=notifications&email_token=AAI75TS6U4PNJ3YGZQBZW73QPFG7NA5CNFSM4JB7ZBE2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUJLWVXI#event-2723637981>,
or unsubscribe

**Pull request merged**
