### PR TITLE
Uncompressed bioresources kb files

### PR DESCRIPTION
**Pull request by enoriega**
Expanded the gz files and modified the code to work this way. After this change, editing the KBs should be easier

### CODE REVIEW

**Review by MihaiSurdeanu — APPROVED** [review]

**Comment by MihaiSurdeanu** [comment]
LGTM!

**Comment by enoriega** [comment]
Thanks for those missing updates @bgyori

**Comment by kwalcock** [comment]
Thanks, @enoriega.  I hadn't intended to create a task for someone else, but if it's already finished, I'll just sit back and be grateful.

**Comment by enoriega** [comment]
Serendipity :)

**Comment by enoriega** [comment]
Unfortunately I already merged. I'll give priority on fixing it to do a new pull request

**Comment by enoriega** [comment]
I ran them on my computer, these are the test suits that need some work:
```
TestAdHocIMKBs
TestProteinResolutions
TestOverrides
```
I started to fixing them now

**Pull request merged**
