### PR TITLE
Use ThreadUtils, now in processors

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
This should also be merged before releasing, right @kwalcock and @enoriega ?

**Review by enoriega — APPROVED** [review]
All changes look good. I like the abstractions in `ThreadUtils`

**Comment by enoriega** [comment]
@MihaiSurdeanu I agree. These changes should be merged before the release

**Comment by MihaiSurdeanu** [comment]
Merged. Thank you @enoriega and @kwalcock !

**Pull request merged**
