### PR TITLE
Variables

### PR DESCRIPTION
**Pull request by zupon**
Finished implementing variables, including singletons for edge cases.
I don't have merging privileges, so if you think it looks good go ahead and merge it.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
1 unit test fails. @zupon: can you please check?

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu fixed

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu @zupon prepositions_subset? They are quite an assortment of prepositions not belonging to any one category, so just saying subset can at least clue people in that this is not **all** prepositions.

**Comment by MihaiSurdeanu** [comment]
Ok... I don't have a better suggestion, so, yes.
It would be great if these variables were described in comments in the vars.yaml file.

**Comment by zupon** [comment]
I changed the name of ${preps} to me more informative, added comments to the variables in vars.yml, and updated the CHANGES file (part of its own pull request).

**Pull request merged**
