### PR TITLE
Resolves #290

### LINKED ISSUE #290: AssemblyCLI has lost ability to read CSV files
AssemblyCLI was used successfully for the last dry run, which included one test in a CSV input file. Now, however, it seems to fail on the exact same input:
```
[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed: Given /Users/hickst/Documents/nxml2fries/papers/PMC1234335.csv, but readNXMLPaper only handles .nxml files!
java.lang.IllegalArgumentException: requirement failed: Given /Users/hickst/Documents/nxml2fries/papers/PMC1234335.csv, but readNXMLPaper only handles .nxml files!
	at scala.Predef$.require(Predef.scala:224)
	at org.clulab.reach.PaperReader$.readPaper(PaperReader.scala:74)
	at org.clulab.reach.PaperReader$.getMentionsFromPaper(PaperReader.scala:81)
	at org.clulab.reach.AssemblyCLI$$anonfun$processPapers$1.apply(AssemblyCLI.scala:51)
	at org.clulab.reach.AssemblyCLI$$anonfun$processPapers$1.apply(AssemblyCLI.scala:42)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
```

### PR DESCRIPTION
**Pull request by myedibleenso**
We can read and output `.csv` or `.tsv` files (again).

### CODE REVIEW

**Comment by myedibleenso** [comment]
I ran this against `PMC1234335.csv` and `PMC3178447.nxml` to ensure we were producing output for both file extensions.

**Comment by hickst** [comment]
I'm getting some compile warnings when trying to compile and test:
```
[info] Compiling 126 Scala sources and 1 Java source to /Users/hickst/workspaceCLU/clulab/reach/target/scala-2.11/classes...
[warn] /Users/hickst/workspaceCLU/clulab/reach/src/main/scala/org/clulab/reach/ReachCSV.scala:39: method toFriesEntries in class DSVParser is deprecated: Use .toFriesEntry to produce a single FriesEntry for the entire paper.
[warn]   for(entry <- csvParser.toFriesEntries(csvFile,
[warn]                          ^
[warn] one warning found
[success] Total time: 33 s, completed Jul 28, 2016 4:00:46 PM
[info] Compiling 45 Scala sources to /Users/hickst/workspaceCLU/clulab/reach/target/scala-2.11/test-classes...
[warn] /Users/hickst/workspaceCLU/clulab/reach/src/test/scala/org/clulab/reach/TestDSVParser.scala:19: method toFriesEntries in class DSVParser is deprecated: Use .toFriesEntry to produce a single FriesEntry for the entire paper.
[warn]     val entries = parser.toFriesEntries(examplePaper)
[warn]                          ^
[warn] one warning found
[success] Total time: 24 s, completed Jul 28, 2016 4:01:10 PM
```

**Comment by myedibleenso** [comment]
Yes, you will.  I didn't add a @deprecated annotation to `.toFriesEntries` as I didn't want to change `ReachCSV` to lump everything together (not sure who needs that and for what purpose).

**Comment by hickst** [comment]
The referenced files probably need to be updated not to use FriesEntries (and this probably coincides with issue #141 from back in March)

**Comment by myedibleenso** [comment]
It only needs to be updated if whoever is using that wants every row in their cvs file to be treated as a single `FriesEntry`.  If so, it just needs to call `.toFriesEntry` instead of `.toFriesEntries` (and at that point `.toFriesEntries` can be deleted).

>and this probably coincides with issue #141 from back in March
No, `ReachCSV` has nothing to do with `ReachCLI` or `AssemblyCLI`.

**Comment by hickst** [comment]
> No, ReachCSV has nothing to do with ReachCLI or AssemblyCLI.

Oh right....jeez...sorry....going to take a nap now.

**Pull request merged**
