### PR TITLE
deleted test

### PR DESCRIPTION
**Pull request by marcovzla**
This test is wrong and it is redundant with tests in processors.
I deleted this one but maybe the whole file should be removed?
The corresponding tests in processors are here: https://github.com/clulab/processors/blob/master/main/src/test/scala/org/clulab/odin/TestTokenPattern.scala

### CODE REVIEW

**Comment by marcovzla** [comment]
I deleted the file since there is a more complete version of these tests in processors.

**Comment by MihaiSurdeanu** [comment]
@marcovzla: So it's safe to update to 6.0.1 now?

**Comment by marcovzla** [comment]
We need to wait until 6.0.1 is available on maven.
It is listed but it gives a 404 for some reason.
I opened an issue here: https://issues.sonatype.org/browse/MVNCENTRAL-1349

**Comment by MihaiSurdeanu** [comment]
@marcovzla, @hickst, @myedibleenso: any updates on this? If not, should we release processors 6.0.2 today?

**Comment by marcovzla** [comment]
The issue was resolved just now. We need to wait around an hour for the artifacts to propagate.

**Pull request merged**
