### PR TITLE
upgrade nxmlreader

### PR DESCRIPTION
**Pull request by marcovzla**
Use new release of nxmlreader. Fixes bugs mentioned in #309.
This pull request won't compile until the new version of nxmlreader becomes available in maven central.

### CODE REVIEW

**Comment by marcovzla** [comment]
I will restart the build in travis once the new nxmlreader becomes available.

**Comment by marcovzla** [comment]
I restarted the build and this time all tests passed.

**Comment by hickst** [comment]
When you say "all tests" what do you mean? I'm still getting these errors on the papers using the lastest Reach master, which includes the nxml reader 0.0.4:
```
==========

 ¡¡¡ NxmlReader error !!!

paper: PMC2228099

error:
java.lang.IllegalArgumentException: requirement failed: children list is empty

stack trace:
scala.Predef$.require(Predef.scala:224)
ai.lum.nxmlreader.standoff.NonTerminal.<init>(Tree.scala:51)
ai.lum.nxmlreader.NxmlDocument.ai$lum$nxmlreader$NxmlDocument$$mkTree$1(NxmlDocument.scala:89)
ai.lum.nxmlreader.NxmlDocument$$anonfun$5.apply(NxmlDocument.scala:83)
ai.lum.nxmlreader.NxmlDocument$$anonfun$5.apply(NxmlDocument.scala:82)
scala.collection.immutable.List.map(List.scala:273)
ai.lum.nxmlreader.NxmlDocument.ai$lum$nxmlreader$NxmlDocument$$mkTree$1(NxmlDocument.scala:82)
ai.lum.nxmlreader.NxmlDocument$$anonfun$5.apply(NxmlDocument.scala:83)
ai.lum.nxmlreader.NxmlDocument$$anonfun$5.apply(NxmlDocument.scala:82)
scala.collection.immutable.List.map(List.scala:273)
ai.lum.nxmlreader.NxmlDocument.ai$lum$nxmlreader$NxmlDocument$$mkTree$1(NxmlDocument.scala:82)
ai.lum.nxmlreader.NxmlDocument$$anonfun$9.apply(NxmlDocument.scala:98)
ai.lum.nxmlreader.NxmlDocument$$anonfun$9.apply(NxmlDocument.scala:98)
scala.Option.map(Option.scala:146)
ai.lum.nxmlreader.NxmlDocument.mkStandoff(NxmlDocument.scala:98)
ai.lum.nxmlreader.NxmlDocument.<init>(NxmlDocument.scala:103)
ai.lum.nxmlreader.NxmlReader.read(NxmlReader.scala:15)
org.clulab.reach.PaperReader$.getEntryFromPaper(PaperReader.scala:105)
org.clulab.reach.ReachCLI.processPaper(ReachCLI.scala:102)
org.clulab.reach.ReachCLI$$anonfun$2.apply(ReachCLI.scala:52)
org.clulab.reach.ReachCLI$$anonfun$2.apply(ReachCLI.scala:48)
scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:657)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:648)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by marcovzla** [comment]
I meant the test in travis. I will fix this and open another pull request.

**Pull request merged**
