### PR TITLE
Global grounding with species from Context

### LINKED ISSUE #103: Sort groundings globally in the 2nd grounding step
Grounding step 2 needs to use context clues to prioritize the best grounding while preserving candidate groundings for future layers.

### PR DESCRIPTION
**Pull request by hickst**
fixes #103

### CODE REVIEW

**Comment by myedibleenso** [comment]
I'll merge as soon as Travis finishes.

**Comment by MihaiSurdeanu** [comment]
Does this include Enrique's backoff strategy to assign most-common species in the document, if no species found by context algo?

**Comment by myedibleenso** [comment]
@MihaiSurdeanu: all the commits appear to be from @hickst.  I'm guessing this might not have @enoriega's back off strategy...is that the case, @hickst?

**Comment by hickst** [comment]
No, this does not yet have Enor's backoff strategy, AFAIK.

**Comment by enoriega** [comment]
It doesn't. The back has it's own branch. I won't require any code modification of this.

**Comment by MihaiSurdeanu** [comment]
But we'd like to use this for the Monday submission. How far are you from a
pull request on that branch?

**Comment by enoriega** [comment]
This night will be issued

**Pull request merged**
