### PR TITLE
Infanticide

### PR DESCRIPTION
**Pull request by myedibleenso**
Removes `assembly` subproject and related output formats.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@myedibleenso : thanks! But I don't understand why the Travis build failed. I can't see any actual test that failed in the log. Do you have any idea? Maybe @kwalcock knows?

**Comment by kwalcock** [comment]
It appears that someone ran out of memory

```
Testing 'main/test' suite...
...
[info] Text6 mentions
[info] - should have sentence bounded species context and groundings (6 milliseconds)
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000583e1e000, 2564104192, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2564104192 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/travis/build/clulab/reach/hs_err_pid5594.log
The 'main/test' suite failed!
```

**Comment by MihaiSurdeanu** [comment]
Thanks!

Given that jenkins was Ok, I will call this a success and merge.

**Comment by myedibleenso** [comment]
@MihaiSurdeanu , sorry for the late response.  I see you've already merged this.  You probably noticed while reviewing, but I wanted to emphasize that this PR also removes the column-based output formats (`arizona`, `cmu`, etc.).  Those all relied on a "light" form of assembly.

Also, considering you've moved to using jenkins, should the travis integration be turn off/removed?  It seems like the project has (or nearly has) outgrown free tier memory limits, no?

**Comment by MihaiSurdeanu** [comment]
Yep, thanks!
We will switch to jenkins completely soon.

**Pull request merged**
