### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by enoriega**
Declared support for Java 11

### CODE REVIEW

**Review by MihaiSurdeanu — APPROVED** [review]

**Comment by kwalcock** [comment]
Someone just found a problem compiling Eidos with Java 11.  Were you able to try Java 11 on reach?

**Comment by enoriega** [comment]
I did not. I read it is possible here: https://github.com/clulab/reach/issues/712
I will verify before merging.

**Comment by kwalcock** [comment]
Ha ha!  Did I write that?  I must have been convinced at the time, but don't remember now.  I trust my former self more than the current one, though.

**Comment by enoriega** [comment]
Weird how updating the README file breaks Jenkins

**Comment by kwalcock** [comment]
I will clean up some old Jenkins builds as well.

**Comment by enoriega** [comment]
I compiled the project, generated a fat jar and ran all tests in my laptop with java 11. I consider it safe. I will merge as soon as GitHub allows it

**Comment by kwalcock** [comment]
I restarted the test.

**Comment by kwalcock** [comment]
@enoriega, that's better.

**Pull request merged**
