### PR TITLE
Update processors to 7.5.0

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks! Let's wait for the tests, then I will release.

**Comment by kwalcock** [comment]
:-(  I'm hoping that one of the other changes that went into processors at the last minute is the problem, or even into processors 7.4.4.  I'll start checking.

**Comment by kwalcock** [comment]
Strange.  It says the tests passed, but there is a lot of red in the output...

**Comment by MihaiSurdeanu** [comment]
I see them still pending...
Let's wait a bit.

**Comment by kwalcock** [comment]
It *looks* like the problem was before the DuoHashTrie PR #311.  It's still being localized.

**Comment by MihaiSurdeanu** [comment]
Thanks!

**Comment by kwalcock** [comment]
The problem is with the AmbivalenceHash.  One line needs to be reverted to make tests pass.  It will be processors 7.5.1 then.

**Comment by MihaiSurdeanu** [comment]
Ok

**Pull request closed without merging**
