### PR TITLE
assembly reassembled

### PR DESCRIPTION
**Pull request by myedibleenso**
Testing reintroduction of assembly, since it seems many aspects were lost when moving to UD.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Hey. I did this already in the branch assembly_is_back. How is this
different?


On August 25, 2020 at 2:19:17 PM, Gus Hahn-Powell (notifications@github.com)
wrote:

Testing reintroduction of assembly, since it seems many aspects were lost
when moving to UD.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/clulab/reach/pull/691
Commit Summary

   - build and ashell
   - Added the assembly subproject
   - CHANGES
   - README
   - tests and conf
   - Reclaiming lost history
   - Updates to assembly
   - Upgrade SBT to 1.x
   - Use lum-ai/common in export

File Changes

   - *M* CHANGES.md
   <https://github.com/clulab/reach/pull/691/files#diff-8b1c3fd0d4a6765c16dfd18509182f9d>
   (1)
   - *M* README.md
   <https://github.com/clulab/reach/pull/691/files#diff-04c6e90faac2675aa89e2176d2eec7d8>
   (47)
   - *A* ashell
   <https://github.com/clulab/reach/pull/691/files#diff-e95d8111b2089898e7f7d266a0d9ecca>
   (2)
   - *A* assembly/CHANGES.md
   <https://github.com/clulab/reach/pull/691/files#diff-a435e8066f33d26851c7e8fa6133e3df>
   (3)
   - *A* assembly/README.md
   <https://github.com/clulab/reach/pull/691/files#diff-0cccf602748c474d784a284c9e0463ba>
   (84)
   - *A* assembly/build.sbt
   <https://github.com/clulab/reach/pull/691/files#diff-9251498fc07d4ec9a8c37d6e97f79aa4>
   (21)
   - *A* assembly/src/main/resources/org/clulab/reach/assembly/fbc.model
   <https://github.com/clulab/reach/pull/691/files#diff-943f5e3711ddd9add451cf76e7242dc1>
   (0)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/grammars/biodrb-patterns.yml
   <https://github.com/clulab/reach/pull/691/files#diff-d98317bc4b777fed952c2166a1ddd9c5>
   (160)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/grammars/intersentential.yml
   <https://github.com/clulab/reach/pull/691/files#diff-7223ef7125d7591b81d2a8f4ea52d9c5>
   (406)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/grammars/intrasentential.yml
   <https://github.com/clulab/reach/pull/691/files#diff-b9232adf5027849a9a8fcc0d418355db>
   (548)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/grammars/mihaila-causal-discourse.yml
   <https://github.com/clulab/reach/pull/691/files#diff-e58803c5649b0d62703c3fdfe2521bb9>
   (82)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/grammars/precedence-markers.yml
   <https://github.com/clulab/reach/pull/691/files#diff-2336898bfe50592604e8dc8f480d4d64>
   (177)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/grammars/tense_aspect.yml
   <https://github.com/clulab/reach/pull/691/files#diff-bab4e73ad577bbf253682d64a07bfeb1>
   (70)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/server/static/annotate.html
   <https://github.com/clulab/reach/pull/691/files#diff-918057d6f6b42c5b68d2b740f210fad9>
   (769)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/server/static/index.html
   <https://github.com/clulab/reach/pull/691/files#diff-f2d088358da4c8b34fb917ccc5aa85be>
   (75)
   - *A*
   assembly/src/main/resources/org/clulab/reach/assembly/server/static/model.html
   <https://github.com/clulab/reach/pull/691/files#diff-71ea8d6c484f5438b4a915fc07383ff4>
   (365)
   - *A* assembly/src/main/resources/reference.conf
   <https://github.com/clulab/reach/pull/691/files#diff-81e255def357902800477b3072ef289f>
   (104)
   - *A* assembly/src/main/scala/org/clulab/reach/assembly/Assembler.scala
   <https://github.com/clulab/reach/pull/691/files#diff-f3c08c65eac42b309fba646b4dd23953>
   (157)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/AssemblyManager.scala
   <https://github.com/clulab/reach/pull/691/files#diff-4d1219e56eacf2b9f81953dcb3520fbd>
   (1929)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/AssemblyShell.scala
   <https://github.com/clulab/reach/pull/691/files#diff-1a6d0bbb36c54b1c94da64becde1f60e>
   (104)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/ParticipantFeatureTracker.scala
   <https://github.com/clulab/reach/pull/691/files#diff-abad95b8f4cc13e30b1cce485599862a>
   (97)
   - *A* assembly/src/main/scala/org/clulab/reach/assembly/RunAssembly.scala
   <https://github.com/clulab/reach/pull/691/files#diff-72f4513da7a25d5c535b33b1677bb373>
   (155)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/display/package.scala
   <https://github.com/clulab/reach/pull/691/files#diff-0845b806a13d9e6fc35f7fe215004a20>
   (43)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/export/AssemblyExporter.scala
   <https://github.com/clulab/reach/pull/691/files#diff-e65efacf31aabac927f154f3e13e9919>
   (419)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/export/AssemblyLink.scala
   <https://github.com/clulab/reach/pull/691/files#diff-361b45f1c186d4e9da3e5a2fe42da4d8>
   (14)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/export/AssemblyRow.scala
   <https://github.com/clulab/reach/pull/691/files#diff-cb525ae5678b76d53d605fa55e058368>
   (155)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/export/ExportFilters.scala
   <https://github.com/clulab/reach/pull/691/files#diff-61c6a5331416dfb1d41578e3d29b795c>
   (135)
   - *A* assembly/src/main/scala/org/clulab/reach/assembly/package.scala
   <https://github.com/clulab/reach/pull/691/files#diff-df2849c0637ae1bb1da1220fdd7a7123>
   (28)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/SieveEvaluator.scala
   <https://github.com/clulab/reach/pull/691/files#diff-424ec755cb425e5f7370c71252e3cc53>
   (406)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/classifier/AssemblyRelationClassifier.scala
   <https://github.com/clulab/reach/pull/691/files#diff-4f5d64f294308cb9e87ffbb1a4956b5b>
   (100)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/classifier/ClassifyAssemblyRelations.scala
   <https://github.com/clulab/reach/pull/691/files#diff-982ede543923d22b35aacb636faf8fbd>
   (241)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/classifier/FeatureExtractor.scala
   <https://github.com/clulab/reach/pull/691/files#diff-03e33506eef3408224681fa795e86e21>
   (657)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/classifier/PathFinder.scala
   <https://github.com/clulab/reach/pull/691/files#diff-d696017ba2550e061b8eb0383769be3c>
   (110)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/corpus/Corpus.scala
   <https://github.com/clulab/reach/pull/691/files#diff-826705120354f7821775962b315ef4e4>
   (210)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/corpus/CorpusBuilder.scala
   <https://github.com/clulab/reach/pull/691/files#diff-8df85f34b09865474dab3dcb591d90f5>
   (249)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/corpus/CorpusReader.scala
   <https://github.com/clulab/reach/pull/691/files#diff-96ca8303a42162fd2d6e17e670fbd308>
   (209)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/relations/corpus/package.scala
   <https://github.com/clulab/reach/pull/691/files#diff-4417c04880c8844146febd0e22ab6e37>
   (39)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/Activation.scala
   <https://github.com/clulab/reach/pull/691/files#diff-f0474300a636e9e7bfb63753a230fbb7>
   (34)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/AssemblyModification.scala
   <https://github.com/clulab/reach/pull/691/files#diff-d89744d531bf5d80fea778de51b74b61>
   (42)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/Complex.scala
   <https://github.com/clulab/reach/pull/691/files#diff-5e172ab33c6c5716cc7500ab4083b0c3>
   (113)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/ComplexEvent.scala
   <https://github.com/clulab/reach/pull/691/files#diff-f9f7df42abd334fb9908d3c5690eff56>
   (147)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/Entity.scala
   <https://github.com/clulab/reach/pull/691/files#diff-c4c18a70528a2463ea5c607e19bed705>
   (15)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/EntityEventRepresentation.scala
   <https://github.com/clulab/reach/pull/691/files#diff-9fc97fc146b1c4b62a16a1b5cc1069ac>
   (118)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/Event.scala
   <https://github.com/clulab/reach/pull/691/files#diff-52aabecdefdca98f899b4c302ebf5877>
   (62)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/Regulation.scala
   <https://github.com/clulab/reach/pull/691/files#diff-9bbaa2429153c5857b06a59b367065d6>
   (31)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/SimpleEntity.scala
   <https://github.com/clulab/reach/pull/691/files#diff-8a91e82a2767ab4f0110440f3a3f3ead>
   (139)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/representations/SimpleEvent.scala
   <https://github.com/clulab/reach/pull/691/files#diff-124c04e5a379cd5066dd34422f9ea4b7>
   (153)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/server/AkkaServerConfig.scala
   <https://github.com/clulab/reach/pull/691/files#diff-44d0baa2d4329f9502bb764810b71d74>
   (29)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/server/AssemblyServer.scala
   <https://github.com/clulab/reach/pull/691/files#diff-fb2a5aa5f6ca259c0f7aa0dc3ecbdda7>
   (46)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/server/Service.scala
   <https://github.com/clulab/reach/pull/691/files#diff-e5198ef63968c5a214e1c051fc936cf2>
   (56)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/server/package.scala
   <https://github.com/clulab/reach/pull/691/files#diff-9bd11cef01cecb6963fb1ec6e3435fe4>
   (23)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/sieves/AssemblyActions.scala
   <https://github.com/clulab/reach/pull/691/files#diff-b65475fef169abb6f55c438fafd0b273>
   (330)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/sieves/AssemblySieve.scala
   <https://github.com/clulab/reach/pull/691/files#diff-9774c5828c276809350f824b686f2ecb>
   (46)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/sieves/Constraints.scala
   <https://github.com/clulab/reach/pull/691/files#diff-c6028a900192dfc04cece2aa5fbb22ed>
   (190)
   - *A*
   assembly/src/main/scala/org/clulab/reach/assembly/sieves/Sieves.scala
   <https://github.com/clulab/reach/pull/691/files#diff-5d01f07c311d6b4d1337592df456bb07>
   (628)
   - *A*
   assembly/src/test/scala/org/clulab/reach/assembly/TestAssemblyManager.scala
   <https://github.com/clulab/reach/pull/691/files#diff-93a36ed9d598ce9d5fbf05a9167e8e7e>
   (444)
   - *A*
   assembly/src/test/scala/org/clulab/reach/assembly/TestAssemblyRules.scala
   <https://github.com/clulab/reach/pull/691/files#diff-1d455a0ad44b61d44cd402c11643bfad>
   (48)
   - *A*
   assembly/src/test/scala/org/clulab/reach/assembly/TestAssemblySieves.scala
   <https://github.com/clulab/reach/pull/691/files#diff-9f46635f3fe74fa914fe3b573a264b39>
   (279)
   - *M* build.sbt
   <https://github.com/clulab/reach/pull/691/files#diff-fdc3abdfd754eeb24090dbd90aeec2ce>
   (10)
   - *M* export/build.sbt
   <https://github.com/clulab/reach/pull/691/files#diff-db4acc5b04ee12acf025e3e508f3facb>
   (2)
   - *M* export/src/main/scala/org/clulab/reach/export/apis/ApiRuler.scala
   <https://github.com/clulab/reach/pull/691/files#diff-52080f01f1262759231deab720306c2a>
   (4)
   - *M*
   export/src/main/scala/org/clulab/reach/export/serial/SerialJsonOutput.scala
   <https://github.com/clulab/reach/pull/691/files#diff-d0d39856e6d58673b0d95913dce21cba>
   (18)
   - *M* main/src/main/resources/application.conf
   <https://github.com/clulab/reach/pull/691/files#diff-60cf7735200e9580292a736571ecf3f3>
   (3)
   - *M* main/src/main/scala/org/clulab/reach/brat/Brat.scala
   <https://github.com/clulab/reach/pull/691/files#diff-d219d19807ff3e31fb035b634c76be5a>
   (16)
   - *M*
   main/src/main/scala/org/clulab/reach/mentions/serialization/json/package.scala
   <https://github.com/clulab/reach/pull/691/files#diff-b370253332a145e5e900f47bfb642f27>
   (2)
   - *M* project/build.properties
   <https://github.com/clulab/reach/pull/691/files#diff-148476c471986e89f6d9100118cb633d>
   (2)
   - *M* project/plugins.sbt
   <https://github.com/clulab/reach/pull/691/files#diff-a84f91f20f040218bccd09fed4761fb3>
   (8)
   - *M* runAllTests.sh
   <https://github.com/clulab/reach/pull/691/files#diff-ea2ee8e0e3e7054effbca650ae68613e>
   (1)
   - *M* src/main/scala/org/clulab/reach/ReachCLI.scala
   <https://github.com/clulab/reach/pull/691/files#diff-4c58f0c9623a8ceb2feab995af33b4d2>
   (23)

Patch Links:

   - https://github.com/clulab/reach/pull/691.patch
   - https://github.com/clulab/reach/pull/691.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/reach/pull/691>, or unsubscribe

**Comment by MihaiSurdeanu** [comment]
@myedibleenso: ignore my message. I see that you added back all the rules.

Let us know if we can help.
@zhengzhongliang : it seems like this PR is more complete than the assembly_is_back branch.

**Comment by myedibleenso** [comment]
There are numerous changes (including the updated rules).  Almost finished I think...

**Comment by MihaiSurdeanu** [comment]
So, what are the next steps? When you give the go ahead, @zhengzhongliang will try to reproduce the rule-based results?

**Comment by myedibleenso** [comment]
@MihaiSurdeanu , rather than hashing it out here, I've sent you and @zhengzhongliang an email outlining my thoughts on next steps.  We can turn that plan into issues if you prefer managing/tracking the work that way.

**Comment by myedibleenso** [comment]
@MihaiSurdeanu , the parameter to `equivalenceHash` determines whether or not modifications factor into equivalence.  If you want these factored in, you would use `true`.  If not, `false`.

**Comment by MihaiSurdeanu** [comment]
Thanks @myedibleenso !

**Comment by MihaiSurdeanu** [comment]
Merged. Thank you @myedibleenso and @kwalcock for your help!

**Comment by MihaiSurdeanu** [comment]
@enoriega: the master branch now has the `cmu` and `arizona` formats as well. Can you please use them for our run?

**Comment by enoriega** [comment]
Yes, I do. Thanks everybody.

**Comment by enoriega** [comment]
I think there is some sneaky bug in there.

After enabling the Arizona and CMU formats, `ReachCLI` is picking up papers, generating the fries output and apparently dropping the ball without actually producing the other output format files. It doesn't report any exceptions nor stack traces.

The log file reports starting the papers but not finishing them. Can someone double check this?

This is the line I have in `application.conf` in case having these formats simultaneously is what triggers the problem:

```
outputTypes = ["fries", "serial-json", "text", "indexcard", "arizona", "cmu"]   
```

**Comment by MihaiSurdeanu** [comment]
Hmm, that is strange.
@kwalcock: can you please create an issue and debug this?
Thank you!

**Pull request merged**
