### PR TITLE
Merge UD into master

### PR DESCRIPTION
**Pull request by maxaalexeeva**
Updated rules to work with Universal Dependencies instead of Stanford Dependencies

### CODE REVIEW

**Comment by myedibleenso** [comment]
@maxaalexeeva, looks like there are two failing tests:
- https://travis-ci.org/clulab/reach/builds/451134650#L4776
- https://travis-ci.org/clulab/reach/builds/451134650#L4899

Can you take a look at those again?

**Comment by maxaalexeeva** [comment]
There are still several changes that need to be made before merging ud into master. Is there going to be a notification/Travis check every time I push now that the pull request has been submitted? Should/can I cancel the pull request for the time being to avoid confusion?

**Comment by MihaiSurdeanu** [comment]
The PR is updated automatically every time you push something to this branch.
So, no need to cancel. But you can cancel it, if you prefer to organize yourself differently. That is, have PRs only when the branch is stable.

**Comment by MihaiSurdeanu** [comment]
@maxaalexeeva: ok to merge then?

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu Travis is running a check for my last push, should be done in 15-20 minutes (I don't know if you can merge while it's running). I don't expect anything to break.

**Comment by MihaiSurdeanu** [comment]
Ok. Please email me when it’s Ok to merge.

**Pull request merged**
