### PR TITLE
Update processors

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Review by MihaiSurdeanu — APPROVED** [review]

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock!
But why tests fail?

**Comment by kwalcock** [comment]
It looks like there were some networking problems and I'll retest in case it goes away:
```
[info] - should POST upload nxml, default output *** FAILED *** (1 second, 39 milliseconds)
[info]   Request was neither completed nor rejected within 1 second (DynamicVariable.scala:58)
```
```
02:04:49.620 [apiserver-akka.actor.default-dispatcher-4] INFO  o.c.reach.export.server.ApiService - Server online at http://localhost:8080
02:04:49.726 [apiserver-akka.actor.default-dispatcher-5] ERROR akka.io.TcpListener - Bind failed for TCP channel on endpoint [localhost/127.0.0.1:8080]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_212]
	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_212]
	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_212]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_212]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_212]
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.io.TcpListener.<init>(TcpListener.scala:53) ~[akka-actor_2.11-2.5.4.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
	at akka.util.Reflect$.instantiate(Reflect.scala:65) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.actor.Props.newActor(Props.scala:213) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:563) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:589) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282) [akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:223) [akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.11-2.5.4.jar:na]
```

**Comment by MihaiSurdeanu** [comment]
Thanks for checking!

**Comment by kwalcock** [comment]
It seems to have worked this time.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !

**Pull request merged**
