### PR TITLE
Issue118

### LINKED ISSUE #118: Coref errors in latest run
I started a big paper run and processed about 1K out of 13K papers before stopping the run (for unrelated reasons). In the first 1K, I got 3 (4?) Coref-related errors (error log file attached).
[log-coref.txt](https://github.com/clulab/reach/files/171326/log-coref.txt)

### PR DESCRIPTION
**Pull request by danebell**
These changes should resolve #118, specifically by 

- adding another failsafe in the DependencyUtils in Reach (and I will now make sure the same change is entered into the Mention utils in Processors because this version should get superceded),
- making sure the logic for mention splitting is sound
- not allowing same-grounding links when either of the mentions has a mutation (even a generic one)

I added a couple of tests to be sure.

### CODE REVIEW

**Comment by myedibleenso** [comment]
Looks like some tests are failing...

**Comment by danebell** [comment]
Ack, they were passing this afternoon. I must have accidentally changed something. I will repair.

**Comment by danebell** [comment]
@myedibleenso Could you check this if you get a chance?

**Comment by myedibleenso** [comment]
@danebell, did you mean that wanted me to take a look at the merge conflict?

```
Auto-merging src/test/scala/edu/arizona/sista/reach/TestCoreference.scala
CONFLICT (content): Merge conflict in src/test/scala/edu/arizona/sista/reach/TestCoreference.scala
Auto-merging src/main/scala/edu/arizona/sista/coref/CorefUtils.scala
Removing src/main/resources/edu/arizona/sista/reach/biogrammar/coref/alias.yml
```

**Comment by danebell** [comment]
No, there were no conflicts when I made the last commit on this. I'll address the conflicts, but then I still need this reviewed. I'll take care of that this morning.

**Pull request merged**
