### PR TITLE
handle n-ary bindings

### PR DESCRIPTION
**Pull request by marcovzla**
Added rule to handle n-ary bindings

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@marcovzla: please add unit tests for this.

**Comment by marcovzla** [comment]
@MihaiSurdeanu I added a test

**Comment by hickst** [comment]
@marcovzla I notice warnings about forced upgrade of Scala 2.11.6 to 2.11.8 in the detail test log (see line 872) BUT all three projects (Biores, Proc, and Reach) have already been manually updated to 2.11.8 so why are you getting these warnings in Travis? Does Travis have its own config files?

**Comment by marcovzla** [comment]
This test will fail until the new version of processors is published

**Comment by MihaiSurdeanu** [comment]
Can you please update dependencies to 5.9.3 for this request?

**Comment by MihaiSurdeanu** [comment]
@myedibleenso: go to bed

**Comment by myedibleenso** [comment]
@marcovzla, I'm sorry.  It seems last night/this morning when I merged `master` into this branch I had a commit (24b7fbc8255cd1274263b53914ce0d474bebc1ca) on my local master which belongs on the `issue284` branch.  That's what I get for working late.   Maybe I should try to unwind this?

**Comment by MihaiSurdeanu** [comment]
Ok to merge this? Seems fine to me.

**Comment by marcovzla** [comment]
will make a new pull request with these changes

**Pull request closed without merging**
