### PR TITLE
Update scala, sbt, plugins, bioresources, processors

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Phew! Lots of stuff going on :)
Thanks @kwalcock !

**Comment by bgyori** [comment]
Hey @keith, looks great! I was wondering, do you think anything in the Dockerfiles (https://github.com/clulab/reach/tree/master/docker) needs to be adapted for these changes? Maybe the scala version being installed in the Dockerfile?

**Comment by kwalcock** [comment]
Good point, @bgyori.  Thanks for watching over me.  Would you like to have Scala 2.12.8 there?

**Comment by kwalcock** [comment]
It looks like I could have used Scala 2.12.12.  sbt 1.4.0 seems to default to that.  Google faked me out by putting 2.12.8 on top.

**Comment by kwalcock** [comment]
It is running out of memory on the Travis tests.  We are also using Jenkins.  Should I unconfigure Travis?

**Comment by MihaiSurdeanu** [comment]
Please do.

**Comment by bgyori** [comment]
> Good point, @bgyori. Thanks for watching over me. Would you like to have Scala 2.12.8 there?

I don't know enough about Scala versions to have an informed response to that, so whatever you think will work best.

**Comment by kwalcock** [comment]
It's still complaining about the port.  I don't see anything else running  Trying again.

**Comment by kwalcock** [comment]
The port was a distractor.  It is failing here:
```
[info] TestReachCLI:
[info] ReachCLI
[info] org.clulab.reach.export.TestReachCLI *** ABORTED *** (3 minutes, 29 seconds)
[info]   java.lang.ExceptionInInitializerError:
[info]   at org.clulab.reach.darpa.DarpaActions.cleanupEvents(DarpaActions.scala:359)
[info]   at org.clulab.reach.ReachSystem.$anonfun$eventEngine$1(ReachSystem.scala:47)
[info]   at org.clulab.odin.ExtractorEngine.extract$1(ExtractorEngine.scala:49)
[info]   at org.clulab.odin.ExtractorEngine.loop$1(ExtractorEngine.scala:34)
[info]   at org.clulab.odin.ExtractorEngine.extractFrom(ExtractorEngine.scala:56)
[info]   at org.clulab.odin.ExtractorEngine.extractByType(ExtractorEngine.scala:63)
[info]   at org.clulab.reach.ReachSystem.extractEventsFrom(ReachSystem.scala:213)
[info]   at org.clulab.reach.ReachSystem.extractFrom(ReachSystem.scala:89)
[info]   at org.clulab.reach.ReachSystem.extractFrom(ReachSystem.scala:155)
[info]   at org.clulab.reach.ReachSystem.extractFrom(ReachSystem.scala:149)
[info]   ...
[info]   Cause: java.lang.NullPointerException:
[info]   at sun.misc.MetaIndex.mayContain(Unknown Source)
[info]   at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
[info]   at sun.misc.URLClassPath.getResource(Unknown Source)
[info]   at sun.misc.URLClassPath.getResource(Unknown Source)
[info]   at java.lang.ClassLoader.getBootstrapResource(Unknown Source)
[info]   at java.lang.ClassLoader.getResource(Unknown Source)
[info]   at xsbt.boot.BootFilteredLoader.getResource(FilteredLoader.scala:24)
[info]   at java.lang.ClassLoader.getResource(Unknown Source)
[info]   at java.lang.ClassLoader.getResource(Unknown Source)
[info]   at java.lang.ClassLoader.getResource(Unknown Source)
[info]   ...
```

**Comment by kwalcock** [comment]
This is slated for imminent merging so that master can be released.  Do any of the other waiting PRs need to be merged before the release?

**Comment by MihaiSurdeanu** [comment]
We're still working on the other 2, so please go ahead!

**Pull request merged**
