### PR TITLE
Fix access to bioresources from jar

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thank you @kwalcock !!

**Comment by kwalcock** [comment]
If/when the tests pass I wonder whether @bgyori can use this branch to test in his environment before I commit.  I did do an assembly use the jar as an unmanaged dependency, but still, things can be different.

**Comment by bgyori** [comment]
I tried this branch and it appears to have fixed the issue, thanks a lot!

**Comment by kwalcock** [comment]
FYI @enoriega, in case you have any reservations.

**Comment by enoriega** [comment]
Looks great. Thanks for fixing the bug

**Pull request merged**
