### PR TITLE
Integrating ChEBI, GO and new stopwords from bioresources

### PR DESCRIPTION
**Pull request by bgyori**
This PR builds on https://github.com/clulab/bioresources/pull/31, https://github.com/clulab/bioresources/pull/32 and https://github.com/clulab/bioresources/pull/33 to add ChEBI as a source of chemical names in addition to PubChem, GO synonyms and names for biological processes, and a new list of stopwords.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@bgyori : this does not build. Is it because it depends on the new bioresources that hasn't been released?

**Comment by bgyori** [comment]
Yes, it depends on 1.1.32-SNAPSHOT.

**Comment by bgyori** [comment]
I am working on some other updates so it probably makes sense to wait before releasing bioresources and merging this.

**Comment by bgyori** [comment]
There are actually more test failures that I can see now, the basic issue is that ChEBI has grounded entries for many very generic terms like `protein`, `inhibitor`, `solution`, etc. that aren't things we want to individually pull out as named entities, especially when they appear in a context such as `the Ras protein`. I am removing some entries from the ChEBI table in bioresources to improve on this issue.

**Comment by bgyori** [comment]
Just changed to the released version of bioresources here so it should build now, let's see if all the tests pass.

**Pull request merged**
