### PR TITLE
Accumulated grounding work.

### PR DESCRIPTION
**Pull request by hickst**
Add enumeration of KB entries (issue #72)
Fixes bioprocess grounding bug (issue #75)
Moves finding of grounding candidates to after modifications.
Enhancements to textual output, and grounding trait.
Numerous cleanups.
Adds test suite for Grounding trait.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Is this where the context tests fail?

**Comment by hickst** [comment]
Maddening thing is that sometimes it fails, sometimes it works. But, since it has failed and sometimes continues to fail on the current master branch, I figure I would go ahead and issue the pull request.

**Comment by MihaiSurdeanu** [comment]
In ReachSystem, I see a new method: mutationsToMentions. Does this conflict with @danebell's work in coref? @hickst and @danebell: can you please double check?
Otherwise, I think it's ready to merge.

**Comment by hickst** [comment]
mutationsToMentions is not new code: I just pulled it out of a function above it as it was a self contained piece of logic.

**Pull request merged**
