### PR TITLE
Issue 328

### PR DESCRIPTION
**Pull request by danebell**
The goal of issue #328 was, broadly, to reintroduce Transcriptions/Expressions and to introduce the related Event types Amount, IncreaseAmount (of which Transcription is a hyponym), and DecreaseAmount. Tests are provided, and exporting and assembly have been altered to allow these events.

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
@danebell: 1 unit test failed here.

**Comment by myedibleenso** [comment]
@danebell, I seem to have "fixed" the index card error.  

I think the index card tests should be disabled.  My impression is that if we ever need to produce index cards again, more work will be needed for them to validate.

**Comment by hickst** [comment]
@myedibleenso I agree: the Indexcard output is way out-of-date and we should "mothball" this code until (IF?) it is ever needed again. The simplest way might be to just comment out its unit tests. We would still update it for major structural changes (i.e. to keep it compiling) but no longer "enhance" it to compete with the FRIES output.

p.s. thanks for fixing the IC output for this change.

**Comment by MihaiSurdeanu** [comment]
@danebell, @myedibleenso: we now fail a bunch of activations, which should be regulations now due to the new Expression events?

**Comment by myedibleenso** [comment]
>which should be regulations now due to the new Expression events?

Probably.  I guess those tests should be adjusted and moved to the Regs suite.  Maybe the Index card test(s) should be commented out as well?

**Comment by MihaiSurdeanu** [comment]
Yep...

**Pull request merged**
